import fs from "node:fs/promises";
import path from "node:path";
import { spawn } from "node:child_process";

const root = process.cwd();
const generated = [];
async function entries(directory) {
  const result = [];
  for (const item of await fs.readdir(directory, { withFileTypes: true })) {
    const file = path.join(directory, item.name);
    if (item.isDirectory()) result.push(...(await entries(file)));
    else if (item.name === "page.tsx" || item.name === "layout.tsx")
      result.push(file);
  }
  return result;
}
try {
  // Render every existing page using its original component and metadata.
  for (const original of await entries(path.join(root, "app"))) {
    const text = await fs.readFile(original, "utf8");
    const exports = ["default"];
    for (const name of [
      "metadata",
      "generateMetadata",
      "generateStaticParams",
      "viewport",
      "generateViewport",
    ]) {
      if (
        new RegExp(
          `export\\s+(?:(?:async\\s+)?function|const)\\s+${name}\\b`,
        ).test(text)
      )
        exports.push(name);
    }
    const target = original.replace(/\.tsx$/, ".preview.tsx");
    await fs.writeFile(
      target,
      `// Generated by scripts/build-review.mjs.\nexport { ${exports.join(", ")} } from "./${path.basename(original, ".tsx")}";\n`,
    );
    generated.push(target);
  }
  const child = spawn(
    process.execPath,
    ["node_modules/next/dist/bin/next", "build"],
    {
      cwd: root,
      stdio: "inherit",
      env: {
        ...process.env,
        PIADS_STATIC_PREVIEW: "1",
        PIADS_BUILD_DIR: "out",
      },
    },
  );
  const code = await new Promise((resolve, reject) => {
    child.on("error", reject);
    child.on("exit", resolve);
  });
  if (code !== 0) throw new Error(`Review export failed (${code})`);
  await fs.access(path.join(root, "out/index.html"));
  await fs.rm(path.join(root, "dist"), { recursive: true, force: true });
  await fs.mkdir(path.join(root, "dist/server"), { recursive: true });
  await fs.cp(path.join(root, "out"), path.join(root, "dist/client"), {
    recursive: true,
  });
  await fs.copyFile(
    path.join(root, "hosting/review-worker.mjs"),
    path.join(root, "dist/server/index.js"),
  );
  await fs.mkdir(path.join(root, "dist/.openai"), { recursive: true });
  await fs.copyFile(
    path.join(root, ".openai/hosting.json"),
    path.join(root, "dist/.openai/hosting.json"),
  );
  console.log(
    "Prepared the complete marketing site and existing API forwarding.",
  );
} finally {
  for (const file of generated) await fs.rm(file, { force: true });
}
